name: Build and test Tasks
on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/Tasks.Api/**'
      - 'src/Tasks.Api.Tests/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/Tasks.Api/**'
      - 'src/Tasks.Api.Tests/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Tasks.Api.Tests/Tasks.Api.Tests.csproj
    - name: Build
      run: dotnet build src/Tasks.Api.Tests/Tasks.Api.Tests.csproj --no-restore
    - name: Test
      run: dotnet test src/Tasks.Api.Tests/Tasks.Api.Tests.csproj --no-build --verbosity normal
